rails g scaffold DeviceState \
Device:belongs_to \
version:string \
armed:boolean \
prearmed:boolean \
mode:string \
status:string \
latitude1:decimal \
longitude1:decimal \
gps1_status:string \
gps1_timestamp:integer \
satcount1:integer \
gps1_altitude:float \
gps1_speed:float \
gps1_heading:float \
gps1_hdop:float \
gps1_fix_type:string \
latitude2:decimal \
longitude2:decimal \
gps2_status:string \
gps2_timestamp:integer \
satcount2:integer \
gps2_altitude:float \
gps2_speed:float \
gps2_heading:float \
gps2_hdop:float \
gps2_fix_type:string \
vibex:float \
vibey:float \
vibez:float \
heading_deg:float \
roll_deg:float \
yaw_deg:float \
landed:boolean \
landed_state:integer \
timeInAir:float \
extended1:boolean \
extend1:boolean \
extended2:boolean \
extend2:boolean \
maglock:boolean \
laser:boolean \
headlight:boolean \
spotlight:boolean \
ax1:float \
ay1:float \
az1:float \
ax2:float \
ay2:float \
az2:float \
ax3:float \
ay3:float \
az3:float \
vx:float \
vy:float \
vz:float \
imu1_temp_c:float \
imu2_temp_c:float \
imu3_temp_c:float \
gimbal_heading_deg:float \
gimbal_tilt_deg:float \
gimbal_yaw_deg:float \
gimbal_target_heading_deg:float \
gimbal_target_tilt_deg:float \
gimbal_target_yaw_deg:float \
nav_bearing:float \
nav_pitch:float \
nav_roll:float \
magnetic_x:float \
magnetic_y:float \
magnetic_z:float \
sonar_range_m:float \
sonar_v:float \
terrainactive:boolean \
safetyactive:boolean \
failsafe:boolean \
temp1_c:float \
temp2_c:float \
temp3_c:float \
temp4_c:float \
temp5_c:float \
temp6_c:float \
temp7_c:float \
temp8_c:float \
pressure_pa:float \
airspeed:float \
battery1_v:float \
battery1_a:float \
battery1_temp_c:float \
battery1_percent:float \
battery2_v:float \
battery2_a:float \
battery2_temp_c:float \
battery2_percent:float \
battery3_v:float \
battery3_a:float \
battery3_temp_c:float \
battery3_percent:float \
battery4_v:float \
battery4_a:float \
battery4_temp_c:float \
battery4_percent:float \
battery5_v:float \
battery5_a:float \
battery5_temp_c:float \
battery5_percent:float \
battery6_v:float \
battery6_a:float \
battery6_temp_c:float \
battery6_percent:float \
battery7_v:float \
battery7_a:float \
battery7_temp_c:float \
battery7_percent:float \
battery8_v:float \
battery8_a:float \
battery8_temp_c:float \
battery8_percent:float \
esc1_v:float \
esc1_a:float \
esc1_temp_c:float \
esc1_rpm:float \
esc2_v:float \
esc2_a:float \
esc2_temp_c:float \
esc2_rpm:float \
esc3_v:float \
esc3_a:float \
esc3_temp_c:float \
esc3_rpm:float \
esc4_v:float \
esc4_a:float \
esc4_temp_c:float \
esc4_rpm:float \
esc5_v:float \
esc5_a:float \
esc5_temp_c:float \
esc5_rpm:float \
esc6_v:float \
esc6_a:float \
esc6_temp_c:float \
esc6_rpm:float \
esc7_v:float \
esc7_a:float \
esc7_temp_c:float \
esc7_rpm:float \
esc8_v:float \
esc8_a:float \
esc8_temp_c:float \
esc8_rpm:float \
esc9_v:float \
esc9_a:float \
esc9_temp_c:float \
esc9_rpm:float \
esc10_v:float \
esc10_a:float \
esc10_temp_c:float \
esc10_rpm:float \
esc11_v:float \
esc11_a:float \
esc11_temp_c:float \
esc11_rpm:float \
esc12_v:float \
esc12_a:float \
esc12_temp_c:float \
esc12_rpm:float \
esc13_v:float \
esc13_a:float \
esc13_temp_c:float \
esc13_rpm:float \
esc14_v:float \
esc14_a:float \
esc14_temp_c:float \
esc14_rpm:float \
esc15_v:float \
esc15_a:float \
esc15_temp_c:float \
esc15_rpm:float \
esc16_v:float \
esc16_a:float \
esc16_temp_c:float \
esc16_rpm:float \
efi_rpm:float \
efi_fuel_pressure_bar:float \
efi_intake_temp_c:float \
efi_exhaust_temp_c:float \
efi_fuel_flow_lps:float \
efi_fuel_percent:float \
efi_baro:float \
efi_load:float \
throttle_angle:float \
brake_angle:float \
steering_wheel_angle:float \
turn_signal:integer \
xpdr_adsb_tx_sys_fail:boolean \
xpdr_airborne_status:boolean \
xpdr_board_temperature_c:float \
xpdr_es1090_tx_enable:boolean \
xpdr_flight_id:string \
xpdr_gps_no_fix:boolean \
xpdr_gps_unavail:boolean \
xpdr_ident_active:boolean \
xpdr_interrogated_since:boolean \
xpdr_maint_req:boolean \
xpdr_mode_A_enable:boolean \
xpdr_mode_A_squawk:integer \
xpdr_mode_C_enable:boolean \
xpdr_mode_S_enable:boolean \
xpdr_nacp:integer \
xpdr_nic:integer \
xpdr_status_pending:boolean \
xpdr_status_unavail:boolean \
xpdr_x_bit_status:boolean \
cell_rssi_dbm:integer \
cell_rsrp:integer \
cell_rsrq:integer \
cell_sinr:integer \
cell_network_type:string \
cell_id:string \
cell_connection_state:string \
cell_network_registration_state:string \
cell_retry_count:integer \
cell_latency_ms:integer \
cell_ip:string \
cell_network_bytes_sent:integer \
cell_network_bytes_recevied:integer \
cell_network_bps_up:integer \
cell_network_bps_down:integer \
wifi_ssid:string \
wifi_bssid:string \
wifi_rssi_dbm:integer \
wifi_snr_db:integer \
wifi_link_speed_mbps:integer \
wifi_band:string \
wifi_channel:integer \
wifi_ip_address:string \
wifi_connection_status:string \
wifi_uptime_sec:integer \
wifi_bytes_sent:integer \
wifi_bytes_received:integer \
mac_address:string \
ethernet_link_status:string \
ethernet_speed:string \
ip_address:string \
subnet_mask:string \
default_gateway:string \
dhcp_status:string \
dhcp_lease:string \
ham_radio_rx_hz:float \
ham_radio_tx_hz:float \
ham_radio_watts:float \
ham_radio_enable:boolean \
ham_radio_v:float \
ham_radio_a:float \
heater1_v:float \
heater1_a:float \
heater1_temp_c:float \
heater2_v:float \
heater2_a:float \
heater2_temp_c:float \
heater3_v:float \
heater3_a:float \
heater3_temp_c:float \
heater4_v:float \
heater4_a:float \
heater4_temp_c:float \
humidity1:float \
humidity2:float \
fan1_v:float \
fan1_a:float \
fan1_rpm:float \
fan2_v:float \
fan2_a:float \
fan2_rpm:float \
rangefinder1_m:float \
rangefinder2_m:float \
rangefinder3_m:float \
rangefinder4_m:float \
rangefinder5_m:float \
rangefinder6_m:float \
rangefinder7_m:float \
rangefinder8_m:float \
solar1_v:float \
solar1_a:float \
solar2_v:float \
solar2_a:float \
charge_v:float \
charge_a:float \
mag1:integer \
mag2:integer \
mag3:integer \
mag4:integer \
button1:boolean \
button2:boolean \
switch1:boolean \
switch2:boolean \
load_cell1_n:float \
load_cell2_n:float \
load_cell3_n:float \
load_cell4_n:float \
current_sensor1_ma:float \
current_sensor2_ma:float \
current_sensor3_ma:float \
current_sensor4_ma:float \
current_sensor5_ma:float \
current_sensor6_ma:float \
current_sensor7_ma:float \
current_sensor8_ma:float \
voltage_sensor1_mv:float \
voltage_sensor2_mv:float \
voltage_sensor3_mv:float \
voltage_sensor4_mv:float \
voltage_sensor5_mv:float \
voltage_sensor6_mv:float \
voltage_sensor7_mv:float \
voltage_sensor9_mv:float \
digital_output1:boolean \
digital_output2:boolean \
digital_output3:boolean \
digital_output4:boolean \
digital_output5:boolean \
digital_output6:boolean \
digital_output7:boolean \
digital_output8:boolean \
digital_input1:boolean \
digital_input2:boolean \
digital_input3:boolean \
digital_input4:boolean \
digital_input5:boolean \
digital_input6:boolean \
digital_input7:boolean \
digital_input8:boolean \
analog_output1:float \
analog_output2:float \
analog_output3:float \
analog_output4:float \
analog_output5:float \
analog_output6:float \
analog_output7:float \
analog_output8:float \
hall1_angle_degrees:float \
hall2_angle_degrees:float \
hall3_angle_degrees:float \
hall4_angle_degrees:float \
hall5_angle_degrees:float \
hall6_angle_degrees:float \
hall7_angle_degrees:float \
hall8_angle_degrees:float \
hall1_presence:boolean \
hall2_presence:boolean \
hall3_presence:boolean \
hall4_presence:boolean \
hall5_presence:boolean \
hall6_presence:boolean \
hall7_presence:boolean \
hall8_presence:boolean \
geiger_mrad:float \
color_r:float \
color_g:float \
color_b:float \
text1:string \
text2:string \
text3:string \
text4:string \
text5:string \
text6:string \
text7:string \
text8:string
